image: docker:stable

stages:
    - build
    - deploy

variables:
    # When using dind service we need to instruct docker, to talk with the
    # daemon started inside of the service. The daemon is available with
    # a network connection instead of the default /var/run/docker.sock socket.
    #
    # The 'docker' hostname is the alias of the service container as described at
    # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
    #
    # Note that if you're using Kubernetes executor, the variable should be set to
    # tcp://localhost:2375 because of how Kubernetes executor connects services
    # to the job container
    DOCKER_HOST: tcp://docker:2375/
    # When using dind, it's wise to use the overlayfs driver for
    # improved performance.
    DOCKER_DRIVER: overlay2
    
services:
    - docker:dind

before_script:
    - docker info
    - apk --no-cache add git
    - apk --no-cache add curl
   - git submodule sync --recursive
   - git submodule foreach --recursive git clean -ffdx
   - git submodule update --init --recursive


build:
    stage: build
    script:
        - docker build -t reinx-builder .
        - docker run -a stdout -a stderr --name reinx-builder -v $(pwd):/developer reinx-builder

publish_nightly:
    stage: deploy
    script:
        - touch /tmp/reinx_build_push_cookie_jar
        - >
          curl -X POST $BASE_URL/user/login -H 'Authorization: Basic cmVpbng6Z3VpZGU=' -H 'cache-control: no-cache'   -H 'content-type: application/x-www-form-urlencoded'   --data "name=$DRUPAL_USER&pass=$DRUPAL_URL_ENCODED_PASSWORD&form_id=user_login_form&op=Log+in" -b /tmp/reinx_build_push_cookie_jar   -c /tmp/reinx_build_push_cookie_jar
        - >
          curl -X GET $BASE_URL/rest/session/token -H 'Authorization: Basic cmVpbng6Z3VpZGU=' -H 'cache-control: no-cache' -b /tmp/reinx_build_push_cookie_jar -c /tmp/reinx_build_push_cookie_jar > /tmp/reinx_build_push_token
        - >
          curl -v -X POST $BASE_URL/node?_format=hal_json -H 'Authorization: Basic cmVpbng6Z3VpZGU=' -H 'Content-type: application/hal+json' -H 'cache-control: no-cache'   -H "X-CSRF-Token: $(cat /tmp/reinx_build_push_token)" -b /tmp/reinx_build_push_cookie_jar   -c /tmp/reinx_build_push_cookie_jar   --data-binary "{\"_links\" : { \"type\" : { \"href\" : \"$BASE_URL/rest/type/node/build\"} },\"type\" : [{\"target_id\":\"build\"}],\"title\" : [{ \"value\" : \"$CI_COMMIT_MESSAGE\" }],\"field_build_download\" : [{ \"uri\" : \"$CI_JOB_URL\" }],\"field_commit_hash\" : [{ \"value\" : \"$CI_COMMIT_SHA\" }],\"field_branch\" : [{ \"value\" : \"$CI_COMMIT_REF_NAME\" }]}"
        - rm /tmp/reinx_build_push_cookie_jar
        - rm /tmp/reinx_build_push_token